/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XcokAmbulance {
    }
}
declare global {
    interface HTMLXcokAmbulanceElement extends Components.XcokAmbulance, HTMLStencilElement {
    }
    var HTMLXcokAmbulanceElement: {
        prototype: HTMLXcokAmbulanceElement;
        new (): HTMLXcokAmbulanceElement;
    };
    interface HTMLElementTagNameMap {
        "xcok-ambulance": HTMLXcokAmbulanceElement;
    }
}
declare namespace LocalJSX {
    interface XcokAmbulance {
    }
    interface IntrinsicElements {
        "xcok-ambulance": XcokAmbulance;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xcok-ambulance": LocalJSX.XcokAmbulance & JSXBase.HTMLAttributes<HTMLXcokAmbulanceElement>;
        }
    }
}
